name: CMake Build and Test

on:
  push:
    branches:
      - main  # Run the workflow on pushes to the 'main' branch
  pull_request:
    branches:
      - main  # Run the workflow on pull requests to the 'main' branch
      
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    container:
      image: gcc:15.1.0  # Official GCC Docker image with GCC 15.1 preinstalled

    steps:
    # Step 1: Checkout the code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Install dependencies
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y lcov git
        wget https://github.com/Kitware/CMake/releases/download/v3.27.0/cmake-3.27.0-linux-x86_64.sh
        sudo bash cmake-3.27.0-linux-x86_64.sh --skip-license --prefix=/usr/local

    # Step 3: Configure, build and run tests
    - name: Configure, build and run tests
      run: |
        rm -rf ./ext
        git clone --depth=1 -b release-1.12.1 https://github.com/google/googletest.git ./ext
        mkdir -p build
        cd ./build
        cmake ..
        cmake --build .
        ctest

