name: CMake Build and Test

on:
  push:
    branches:
      - main  # Run the workflow on pushes to the 'main' branch
  pull_request:
    branches:
      - main  # Run the workflow on pull requests to the 'main' branch
      
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    container:
      image: gcc:15.1.0  # Official GCC Docker image with GCC 15.1 preinstalled

    steps:
    # Step 1: Checkout the code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Install dependencies
    - name: Install dependencies
      run: apt-get update && apt-get install -y cmake lcov

    # Step 3: Verify GCC version
    - name: Check GCC version
      run: |
        gcc --version
        g++ --version

    # Step 4: Configure the project with CMake
    - name: Configure with CMake
      run: cmake -S . -B build -DCMAKE_CXX_STANDARD=26 -DCMAKE_CXX_STANDARD_REQUIRED=ON

    # Step 5: Build the project
    - name: Build the project
      run: cmake --build build

    # Step 6: Run tests
    - name: Run tests
      run: ctest --test-dir build --output-on-failure